### ISSUE TITLE
Error when uploading an image

### ISSUE THREAD

**Issue by joshmarinacci** [mdn/developer-portal#947] opened 2019-12-05 17:57 UTC
**Describe the bug**
I'm trying to upload an image to the portal and I get 500 error.

**To Reproduce**
1. Pick a post to edit
2. use the button to pick a feature image
3. switch to the 'upload' tab
4. pick a local image.
5. click upload.

**Expected behavior**
image is uploaded

**Screenshots**

<img width="1358" alt="emulator-upload" src="https://user-images.githubusercontent.com/276938/70260562-669d7980-1745-11ea-97e3-2846a697b87e.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version latest Nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stevejalim** [comment] 2019-12-05 18:09
Looks like this is related to our pinned Willow dependency (1.1) - am removing the constraint so that we just get whatever Wagtail needs

**Comment by stevejalim** [comment] 2019-12-05 23:01
Resolved in d88c184 which is being deployed to production now. Confirmed working fine on staging.

**Closed by stevejalim** 2019-12-05 23:01 UTC
