### ISSUE TITLE
As a visitor viewing old events, I want to see associated talk videos so that . . . 

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1458] opened 2020-05-12 08:08 UTC
As a visitor viewing old events, I want to see associated talk videos so that I can learn from them and decide if I want to attend a future edition of the event

AC
- [ ] We now have a videos section to Event detail pages
  - Above the newsletter footer
  - Below the description and image
  - Design should be identical to the What we're developing / What we're working on section for Topic pages.

- [ ] (Added by @stevejalim): if the video is an ExternalVideo, it plays in a lightbox on the page. If the video is hosted within the CMS, the link takes the user to the standalone Video page

- [ ] Plus: ability to add a button on the bottom right (sidebar, below Event image) that reads "View content from this event" which can be linked to a content page

**Comment by stevejalim** [comment] 2020-06-23 11:11
@valgrimm Could you clarify a bit more (or just provide a screenshot with a box on it) so I can get into the same headspace for this point, please?  

> ability to add a button on the bottom right that reads "View more" which can be linked to a content page

**Comment by stevejalim** [comment] 2020-07-03 11:00
@valgrimm Is this a duplicate of #1252, please?

**Comment by valgrimm** [comment] 2020-07-03 12:16
*facepalm* yes, minus the "Watch More" link that should be added to 1252. Good catch!

**Comment by stevejalim** [comment] 2020-07-03 12:19
Duplicated by #1252 - closing this one

**Closed by stevejalim** 2020-07-03 12:19 UTC
