### ISSUE TITLE
Support upload of non-image files

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#907] opened 2019-11-29 14:58 UTC
Example:
A presenter gives Val a Powerpoint or PDF of their slides.
Val uploads this to Wagtail. 
Val creates a "external link" to this page or a File page (related to 905)
Val links to this file from an event page as an "External content" > Files type (related to 905)

**Comment by stevejalim** [comment] 2019-11-29 14:59
Is this a duplicate of #545 ?

**Comment by valgrimm** [comment] 2019-11-29 15:04
Supports 545

**Comment by atopal** [comment] 2019-12-02 14:27
we'll use 545 as the epic.

**Closed by atopal** 2019-12-02 14:27 UTC
